- 1.1.14
- _NAME: Signature M650 L
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, persistent-remappable-keys, disable-keyboard-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures,
    gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B02A00000000
  _sensitive: {dpi: true}
  _serial: A717C369
  _unitId: A717C369
  _wpid: B02A
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0}
  dpi: 800
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86}
- _NAME: Pebble Keys 2 K380s
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight, backlight_level,
    backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_,
    brightness_control, per-key-lighting, reprogrammable-keys, persistent-remappable-keys, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led,
    gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B37700000000
  _sensitive: {divert-keys: true, multiplatform: false}
  _serial: 143C62D3
  _unitId: 143C62D3
  _wpid: B377
  change-host: null
  disable-keyboard-keys: {1: false, 8: false, 16: false}
  divert-keys: {110: 0, 206: 1, 212: 1, 229: 0, 231: 0, 232: 0, 233: 0, 259: 1, 264: 1, 266: 1, 279: 0}
  fn-swap: false
  multiplatform: 0
