monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.*ARTURIA.*" }
    ]
    actions = {
      update-props = {
        api.alsa.use-ucm = false
      }
    }
  }
  {
    matches = [
      { node.name = "~alsa_output.*ARTURIA.*" }
      { node.name = "~alsa_input.*ARTURIA.*" }
    ]
    actions = {
      update-props = {
        api.alsa.period-size            = 128
        api.alsa.headroom               = 0
        api.alsa.disable-batch          = true
        session.suspend-timeout-seconds = 0
        node.pause-on-idle              = false
      }
    }
  }
]
