monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.pci-.*analog-stereo" }
      { node.name = "~alsa_input.pci-.*analog-stereo" }
    ]
    actions = {
      update-props = {
        api.alsa.period-size            = 1024
        api.alsa.headroom               = 0
        session.suspend-timeout-seconds = 0
        node.pause-on-idle              = false
      }
    }
  }
]
